### ISSUE TITLE
Release GoodJob 4.0

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#764]
## Upgrade blocking application needs

- [x] Application developers need to ensure that all unfinished jobs are "discrete". This means ensuring being up to date on database migrations, and then running through all jobs. 
  - [x] TODO: have a `GoodJob.v4_ready?` check

## Deprecations

- [x] Remove support for JRuby 9.2. Done in #756
- [x] Remove support for C Ruby < 3.0 and JRuby <  9.4. This gets us entirely on Ruby 3.0 compatible syntax 😰 

## After migration

- [x] Publish a discussion post: https://github.com/bensheldon/good_job/discussions/1396
- [x] Publish a blog post: https://island94.org/2024/07/introducing-goodjob-v4
- [x] Post on Ruby.Social: https://ruby.social/@bensheldon/112743421143107997
- [x] Post on Reddit (r/rails): https://www.reddit.com/r/rails/comments/1dxncuq/introducing_goodjob_v4/
- [ ] Ruby Weekly (picked up via Reddit)
- [ ] Short Ruby (Picked up via Reddit / Mastodon)
- [x] Ruby Land (via island94.org)
- [x] Ruby Flow https://rubyflow.com/p/l5uf9h-goodjob-v4-
- [x] GitHub Release Radar: https://github.com/github/release-radar/issues/223

## Blocked features
- [ ] Using labels for concurrency rules
- [ ] Can add paused jobs: #1323
